# Generated by Django 4.1 on 2022-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=10)),
                ('desc', models.TextField(max_length=100)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
